using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.ObjectModel;
using System.Linq.Expressions;
using MedicalResearch.StudyManagement.Model;

namespace MedicalResearch.StudyManagement.Persistence {

public class InstituteEntity {

  /// <summary> An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more! </summary>
  [Required]
  public Guid InstituteUid { get; set; } = Guid.NewGuid();

  /// <summary> An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. *this field has a max length of 100 </summary>
  [MaxLength(100), Required]
  public String DisplayLabel { get; set; }

  [Required]
  public Boolean IsArchived { get; set; }

  [Referer]
  public virtual ObservableCollection<ResearchStudyEntity> InitiatedStudies { get; set; } = new ObservableCollection<ResearchStudyEntity>();

  [Referer]
  public virtual ObservableCollection<SiteEntity> RepresentedSites { get; set; } = new ObservableCollection<SiteEntity>();

  [Dependent]
  public virtual ObservableCollection<SystemEndpointEntity> ProvidedSystemEndpoints { get; set; } = new ObservableCollection<SystemEndpointEntity>();

  [Dependent]
  public virtual ObservableCollection<InstituteRelatedSystemAssignmentEntity> SystemAssignment { get; set; } = new ObservableCollection<InstituteRelatedSystemAssignmentEntity>();

  [Dependent]
  public virtual ObservableCollection<SystemConnectionEntity> SystemConnections { get; set; } = new ObservableCollection<SystemConnectionEntity>();

#region Mapping

  internal static Expression<Func<Institute, InstituteEntity>> InstituteEntitySelector = ((Institute src) => new InstituteEntity {
    InstituteUid = src.InstituteUid,
    DisplayLabel = src.DisplayLabel,
    IsArchived = src.IsArchived,
  });

  internal static Expression<Func<InstituteEntity, Institute>> InstituteSelector = ((InstituteEntity src) => new Institute {
    InstituteUid = src.InstituteUid,
    DisplayLabel = src.DisplayLabel,
    IsArchived = src.IsArchived,
  });

  internal void CopyContentFrom(Institute source, Func<String,bool> onFixedValueChangingCallback = null){
    this.InstituteUid = source.InstituteUid;
    this.DisplayLabel = source.DisplayLabel;
    this.IsArchived = source.IsArchived;
  }

  internal void CopyContentTo(Institute target, Func<String,bool> onFixedValueChangingCallback = null){
    target.InstituteUid = this.InstituteUid;
    target.DisplayLabel = this.DisplayLabel;
    target.IsArchived = this.IsArchived;
  }

#endregion

}

/// <summary> entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see> </summary>
public class ResearchStudyEntity {

  /// <summary> An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more! </summary>
  [Required]
  public Guid ResearchStudyUid { get; set; } = Guid.NewGuid();

  /// <summary> An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. *this field has a max length of 100 </summary>
  [MaxLength(100), Required]
  public String DisplayLabel { get; set; }

  [Required]
  public Guid InitiatorInstituteUid { get; set; }

  [Required]
  public String StudyWorkflowName { get; set; }

  [Required]
  public String StudyWorkflowVersion { get; set; }

  /// <summary> AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-study-phase.html">HL7.ResearchStudyPhase</see>:
  /// n-a | early-phase-1 | phase-1 | phase-1-phase-2 | phase-2 | phase-2-phase-3 | phase-3 | phase-4 *this field is optional (use null as value) </summary>
  public String Phase { get; set; }

  /// <summary> a estimated date in future is possible *this field is optional </summary>
  public Nullable<DateTime> StartDate { get; set; }

  /// <summary> a estimated date in future is possible *this field is optional </summary>
  public Nullable<DateTime> TerminationDate { get; set; }

  /// <summary> A title which informs about the sematic of the SubjectIdentifer (which concrete value is used): "Randomization-Number", "Screening-Number", ... </summary>
  [Required]
  public String SubjectIdentifierTitle { get; set; }

  /// <summary> AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-study-status.html">HL7.ResearchStudyStatus</see>:
  /// active | administratively-completed | approved | closed-to-accrual | closed-to-accrual-and-intervention | completed | disapproved | in-review | temporarily-closed-to-accrual | temporarily-closed-to-accrual-and-intervention | withdrawn </summary>
  [Required]
  public String Status { get; set; }

  /// <summary> *this field is optional (use null as value) </summary>
  public String TerminatedReason { get; set; }

  [Required]
  public Boolean IsArchived { get; set; }

  /// <summary> *this field is optional (use null as value) </summary>
  public String InitiatorRelatedProjectNumber { get; set; }

  /// <summary> *this field is optional </summary>
  public Nullable<Guid> OriginWdrEndpointUid { get; set; }

  [Lookup]
  public virtual InstituteEntity InitiatorInstitute { get; set; }

  [Dependent]
  public virtual ObservableCollection<InvolvementRoleEntity> InvolvementRoles { get; set; } = new ObservableCollection<InvolvementRoleEntity>();

  [Dependent]
  public virtual ObservableCollection<SiteEntity> Sites { get; set; } = new ObservableCollection<SiteEntity>();

  [Lookup]
  public virtual SystemEndpointEntity OriginWdr { get; set; }

  [Dependent]
  public virtual ObservableCollection<StudyRelatedSystemAssignmentEntity> SystemAssignments { get; set; } = new ObservableCollection<StudyRelatedSystemAssignmentEntity>();

#region Mapping

  internal static Expression<Func<ResearchStudy, ResearchStudyEntity>> ResearchStudyEntitySelector = ((ResearchStudy src) => new ResearchStudyEntity {
    ResearchStudyUid = src.ResearchStudyUid,
    DisplayLabel = src.DisplayLabel,
    InitiatorInstituteUid = src.InitiatorInstituteUid,
    StudyWorkflowName = src.StudyWorkflowName,
    StudyWorkflowVersion = src.StudyWorkflowVersion,
    Phase = src.Phase,
    StartDate = src.StartDate,
    TerminationDate = src.TerminationDate,
    SubjectIdentifierTitle = src.SubjectIdentifierTitle,
    Status = src.Status,
    TerminatedReason = src.TerminatedReason,
    IsArchived = src.IsArchived,
    InitiatorRelatedProjectNumber = src.InitiatorRelatedProjectNumber,
    OriginWdrEndpointUid = src.OriginWdrEndpointUid,
  });

  internal static Expression<Func<ResearchStudyEntity, ResearchStudy>> ResearchStudySelector = ((ResearchStudyEntity src) => new ResearchStudy {
    ResearchStudyUid = src.ResearchStudyUid,
    DisplayLabel = src.DisplayLabel,
    InitiatorInstituteUid = src.InitiatorInstituteUid,
    StudyWorkflowName = src.StudyWorkflowName,
    StudyWorkflowVersion = src.StudyWorkflowVersion,
    Phase = src.Phase,
    StartDate = src.StartDate,
    TerminationDate = src.TerminationDate,
    SubjectIdentifierTitle = src.SubjectIdentifierTitle,
    Status = src.Status,
    TerminatedReason = src.TerminatedReason,
    IsArchived = src.IsArchived,
    InitiatorRelatedProjectNumber = src.InitiatorRelatedProjectNumber,
    OriginWdrEndpointUid = src.OriginWdrEndpointUid,
  });

  internal void CopyContentFrom(ResearchStudy source, Func<String,bool> onFixedValueChangingCallback = null){
    this.ResearchStudyUid = source.ResearchStudyUid;
    this.DisplayLabel = source.DisplayLabel;
    this.InitiatorInstituteUid = source.InitiatorInstituteUid;
    this.StudyWorkflowName = source.StudyWorkflowName;
    this.StudyWorkflowVersion = source.StudyWorkflowVersion;
    this.Phase = source.Phase;
    this.StartDate = source.StartDate;
    this.TerminationDate = source.TerminationDate;
    this.SubjectIdentifierTitle = source.SubjectIdentifierTitle;
    this.Status = source.Status;
    this.TerminatedReason = source.TerminatedReason;
    this.IsArchived = source.IsArchived;
    this.InitiatorRelatedProjectNumber = source.InitiatorRelatedProjectNumber;
    this.OriginWdrEndpointUid = source.OriginWdrEndpointUid;
  }

  internal void CopyContentTo(ResearchStudy target, Func<String,bool> onFixedValueChangingCallback = null){
    target.ResearchStudyUid = this.ResearchStudyUid;
    target.DisplayLabel = this.DisplayLabel;
    target.InitiatorInstituteUid = this.InitiatorInstituteUid;
    target.StudyWorkflowName = this.StudyWorkflowName;
    target.StudyWorkflowVersion = this.StudyWorkflowVersion;
    target.Phase = this.Phase;
    target.StartDate = this.StartDate;
    target.TerminationDate = this.TerminationDate;
    target.SubjectIdentifierTitle = this.SubjectIdentifierTitle;
    target.Status = this.Status;
    target.TerminatedReason = this.TerminatedReason;
    target.IsArchived = this.IsArchived;
    target.InitiatorRelatedProjectNumber = this.InitiatorRelatedProjectNumber;
    target.OriginWdrEndpointUid = this.OriginWdrEndpointUid;
  }

#endregion

}

public class SiteEntity {

  /// <summary> An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more! </summary>
  [Required]
  public Guid SiteUid { get; set; } = Guid.NewGuid();

  /// <summary> <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> of the institute, which is representing this site </summary>
  [Required]
  public Guid RepresentingInstituteUid { get; set; }

  /// <summary> <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> of the related record </summary>
  [Required]
  public Guid ResearchStudyUid { get; set; }

  /// <summary> a estimated date in future is possible *this field is optional </summary>
  public Nullable<DateTime> EnrollmentDate { get; set; }

  /// <summary> a estimated date in future is possible *this field is optional </summary>
  public Nullable<DateTime> TerminationDate { get; set; }

  /// <summary> *this field is optional (use null as value) </summary>
  public String TerminatedReason { get; set; }

  /// <summary> Offical 'SiteIdentifier' which is unique within the scope of the related study </summary>
  [Required]
  public String StudyRelatedSiteIdentifer { get; set; }

  /// <summary> An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. </summary>
  [Required]
  public String DisplayLabel { get; set; }

  /// <summary> AS DECLARED BY HL7 </summary>
  [Required]
  public String Status { get; set; }

  /// <summary> *this field is optional (use null as value) </summary>
  public String SiteRelatedProjectNumber { get; set; }

  [Lookup]
  public virtual InstituteEntity RepresentingInstitute { get; set; }

  [Referer]
  public virtual ObservableCollection<InvolvementRoleEntity> SiteDedicatedInvolvementRoles { get; set; } = new ObservableCollection<InvolvementRoleEntity>();

  [Principal]
  public virtual ResearchStudyEntity Study { get; set; }

  [Dependent]
  public virtual ObservableCollection<SiteRelatedSystemAssignmentEntity> SystemAssignments { get; set; } = new ObservableCollection<SiteRelatedSystemAssignmentEntity>();

#region Mapping

  internal static Expression<Func<Site, SiteEntity>> SiteEntitySelector = ((Site src) => new SiteEntity {
    SiteUid = src.SiteUid,
    RepresentingInstituteUid = src.RepresentingInstituteUid,
    ResearchStudyUid = src.ResearchStudyUid,
    EnrollmentDate = src.EnrollmentDate,
    TerminationDate = src.TerminationDate,
    TerminatedReason = src.TerminatedReason,
    StudyRelatedSiteIdentifer = src.StudyRelatedSiteIdentifer,
    DisplayLabel = src.DisplayLabel,
    Status = src.Status,
    SiteRelatedProjectNumber = src.SiteRelatedProjectNumber,
  });

  internal static Expression<Func<SiteEntity, Site>> SiteSelector = ((SiteEntity src) => new Site {
    SiteUid = src.SiteUid,
    RepresentingInstituteUid = src.RepresentingInstituteUid,
    ResearchStudyUid = src.ResearchStudyUid,
    EnrollmentDate = src.EnrollmentDate,
    TerminationDate = src.TerminationDate,
    TerminatedReason = src.TerminatedReason,
    StudyRelatedSiteIdentifer = src.StudyRelatedSiteIdentifer,
    DisplayLabel = src.DisplayLabel,
    Status = src.Status,
    SiteRelatedProjectNumber = src.SiteRelatedProjectNumber,
  });

  internal void CopyContentFrom(Site source, Func<String,bool> onFixedValueChangingCallback = null){
    this.SiteUid = source.SiteUid;
    this.RepresentingInstituteUid = source.RepresentingInstituteUid;
    this.ResearchStudyUid = source.ResearchStudyUid;
    this.EnrollmentDate = source.EnrollmentDate;
    this.TerminationDate = source.TerminationDate;
    this.TerminatedReason = source.TerminatedReason;
    this.StudyRelatedSiteIdentifer = source.StudyRelatedSiteIdentifer;
    this.DisplayLabel = source.DisplayLabel;
    this.Status = source.Status;
    this.SiteRelatedProjectNumber = source.SiteRelatedProjectNumber;
  }

  internal void CopyContentTo(Site target, Func<String,bool> onFixedValueChangingCallback = null){
    target.SiteUid = this.SiteUid;
    target.RepresentingInstituteUid = this.RepresentingInstituteUid;
    target.ResearchStudyUid = this.ResearchStudyUid;
    target.EnrollmentDate = this.EnrollmentDate;
    target.TerminationDate = this.TerminationDate;
    target.TerminatedReason = this.TerminatedReason;
    target.StudyRelatedSiteIdentifer = this.StudyRelatedSiteIdentifer;
    target.DisplayLabel = this.DisplayLabel;
    target.Status = this.Status;
    target.SiteRelatedProjectNumber = this.SiteRelatedProjectNumber;
  }

#endregion

}

public class SystemEndpointEntity {

  [Required]
  public Guid SystemEndpointUid { get; set; } = Guid.NewGuid();

  [Required]
  public Guid ProviderInstituteUid { get; set; }

  [Required]
  public String AvailableRoles { get; set; }

  [Required]
  public String Url { get; set; }

  [Required]
  public String ApprovedCert { get; set; }

  [Required]
  public String IsPublic { get; set; }

  [Required]
  public String Label { get; set; }

  [Principal]
  public virtual InstituteEntity ProviderInstitute { get; set; }

  [Referer]
  public virtual ObservableCollection<InstituteRelatedSystemAssignmentEntity> InstituteAssignments { get; set; } = new ObservableCollection<InstituteRelatedSystemAssignmentEntity>();

  [Referer]
  public virtual ObservableCollection<SiteRelatedSystemAssignmentEntity> SiteAssignments { get; set; } = new ObservableCollection<SiteRelatedSystemAssignmentEntity>();

  [Referer]
  public virtual ObservableCollection<StudyRelatedSystemAssignmentEntity> StudyAssignments { get; set; } = new ObservableCollection<StudyRelatedSystemAssignmentEntity>();

#region Mapping

  internal static Expression<Func<SystemEndpoint, SystemEndpointEntity>> SystemEndpointEntitySelector = ((SystemEndpoint src) => new SystemEndpointEntity {
    SystemEndpointUid = src.SystemEndpointUid,
    ProviderInstituteUid = src.ProviderInstituteUid,
    AvailableRoles = src.AvailableRoles,
    Url = src.Url,
    ApprovedCert = src.ApprovedCert,
    IsPublic = src.IsPublic,
    Label = src.Label,
  });

  internal static Expression<Func<SystemEndpointEntity, SystemEndpoint>> SystemEndpointSelector = ((SystemEndpointEntity src) => new SystemEndpoint {
    SystemEndpointUid = src.SystemEndpointUid,
    ProviderInstituteUid = src.ProviderInstituteUid,
    AvailableRoles = src.AvailableRoles,
    Url = src.Url,
    ApprovedCert = src.ApprovedCert,
    IsPublic = src.IsPublic,
    Label = src.Label,
  });

  internal void CopyContentFrom(SystemEndpoint source, Func<String,bool> onFixedValueChangingCallback = null){
    this.SystemEndpointUid = source.SystemEndpointUid;
    this.ProviderInstituteUid = source.ProviderInstituteUid;
    this.AvailableRoles = source.AvailableRoles;
    this.Url = source.Url;
    this.ApprovedCert = source.ApprovedCert;
    this.IsPublic = source.IsPublic;
    this.Label = source.Label;
  }

  internal void CopyContentTo(SystemEndpoint target, Func<String,bool> onFixedValueChangingCallback = null){
    target.SystemEndpointUid = this.SystemEndpointUid;
    target.ProviderInstituteUid = this.ProviderInstituteUid;
    target.AvailableRoles = this.AvailableRoles;
    target.Url = this.Url;
    target.ApprovedCert = this.ApprovedCert;
    target.IsPublic = this.IsPublic;
    target.Label = this.Label;
  }

#endregion

}

public class InstituteRelatedSystemAssignmentEntity {

  [Required]
  public Guid InstituteRelatedSystemAssignemntUid { get; set; } = Guid.NewGuid();

  [Required]
  public Guid SystemEndpointUid { get; set; }

  [Required]
  public Guid InstituteUid { get; set; }

  [Required]
  public String UseAsOwnPatientSdr { get; set; }

  [Required]
  public String UseAsCandidateSdr { get; set; }

  [Required]
  public String UseAsOwnWdr { get; set; }

  [Required]
  public String UseAsConsumingExternalWdr { get; set; }

  /// <summary> semicolon separated list of custom role-names </summary>
  [Required]
  public String CustomRoles { get; set; }

  [Principal]
  public virtual InstituteEntity Institute { get; set; }

  [Lookup]
  public virtual SystemEndpointEntity SystemEndpoint { get; set; }

#region Mapping

  internal static Expression<Func<InstituteRelatedSystemAssignment, InstituteRelatedSystemAssignmentEntity>> InstituteRelatedSystemAssignmentEntitySelector = ((InstituteRelatedSystemAssignment src) => new InstituteRelatedSystemAssignmentEntity {
    InstituteRelatedSystemAssignemntUid = src.InstituteRelatedSystemAssignemntUid,
    SystemEndpointUid = src.SystemEndpointUid,
    InstituteUid = src.InstituteUid,
    UseAsOwnPatientSdr = src.UseAsOwnPatientSdr,
    UseAsCandidateSdr = src.UseAsCandidateSdr,
    UseAsOwnWdr = src.UseAsOwnWdr,
    UseAsConsumingExternalWdr = src.UseAsConsumingExternalWdr,
    CustomRoles = src.CustomRoles,
  });

  internal static Expression<Func<InstituteRelatedSystemAssignmentEntity, InstituteRelatedSystemAssignment>> InstituteRelatedSystemAssignmentSelector = ((InstituteRelatedSystemAssignmentEntity src) => new InstituteRelatedSystemAssignment {
    InstituteRelatedSystemAssignemntUid = src.InstituteRelatedSystemAssignemntUid,
    SystemEndpointUid = src.SystemEndpointUid,
    InstituteUid = src.InstituteUid,
    UseAsOwnPatientSdr = src.UseAsOwnPatientSdr,
    UseAsCandidateSdr = src.UseAsCandidateSdr,
    UseAsOwnWdr = src.UseAsOwnWdr,
    UseAsConsumingExternalWdr = src.UseAsConsumingExternalWdr,
    CustomRoles = src.CustomRoles,
  });

  internal void CopyContentFrom(InstituteRelatedSystemAssignment source, Func<String,bool> onFixedValueChangingCallback = null){
    this.InstituteRelatedSystemAssignemntUid = source.InstituteRelatedSystemAssignemntUid;
    this.SystemEndpointUid = source.SystemEndpointUid;
    this.InstituteUid = source.InstituteUid;
    this.UseAsOwnPatientSdr = source.UseAsOwnPatientSdr;
    this.UseAsCandidateSdr = source.UseAsCandidateSdr;
    this.UseAsOwnWdr = source.UseAsOwnWdr;
    this.UseAsConsumingExternalWdr = source.UseAsConsumingExternalWdr;
    this.CustomRoles = source.CustomRoles;
  }

  internal void CopyContentTo(InstituteRelatedSystemAssignment target, Func<String,bool> onFixedValueChangingCallback = null){
    target.InstituteRelatedSystemAssignemntUid = this.InstituteRelatedSystemAssignemntUid;
    target.SystemEndpointUid = this.SystemEndpointUid;
    target.InstituteUid = this.InstituteUid;
    target.UseAsOwnPatientSdr = this.UseAsOwnPatientSdr;
    target.UseAsCandidateSdr = this.UseAsCandidateSdr;
    target.UseAsOwnWdr = this.UseAsOwnWdr;
    target.UseAsConsumingExternalWdr = this.UseAsConsumingExternalWdr;
    target.CustomRoles = this.CustomRoles;
  }

#endregion

}

public class SystemConnectionEntity {

  [Required]
  public Guid SystemConnectionUid { get; set; } = Guid.NewGuid();

  [Required]
  public Guid OwnerInstituteUid { get; set; }

  [Required]
  public String HierSpäterJWTSEttings { get; set; }

  [Required]
  public Guid TargetSystemEndpointUid { get; set; }

  /// <summary> *this field is optional </summary>
  public Nullable<Guid> DedicatedSiteRelatedSystemAssignmentUid { get; set; }

  [Principal]
  public virtual InstituteEntity OwnerInstitute { get; set; }

  [Lookup]
  public virtual SiteRelatedSystemAssignmentEntity DedicatedSiteRelatedSystemAssignment { get; set; }

  [Lookup]
  public virtual SystemEndpointEntity TargetEndpoint { get; set; }

#region Mapping

  internal static Expression<Func<SystemConnection, SystemConnectionEntity>> SystemConnectionEntitySelector = ((SystemConnection src) => new SystemConnectionEntity {
    SystemConnectionUid = src.SystemConnectionUid,
    OwnerInstituteUid = src.OwnerInstituteUid,
    HierSpäterJWTSEttings = src.HierSpäterJWTSEttings,
    TargetSystemEndpointUid = src.TargetSystemEndpointUid,
    DedicatedSiteRelatedSystemAssignmentUid = src.DedicatedSiteRelatedSystemAssignmentUid,
  });

  internal static Expression<Func<SystemConnectionEntity, SystemConnection>> SystemConnectionSelector = ((SystemConnectionEntity src) => new SystemConnection {
    SystemConnectionUid = src.SystemConnectionUid,
    OwnerInstituteUid = src.OwnerInstituteUid,
    HierSpäterJWTSEttings = src.HierSpäterJWTSEttings,
    TargetSystemEndpointUid = src.TargetSystemEndpointUid,
    DedicatedSiteRelatedSystemAssignmentUid = src.DedicatedSiteRelatedSystemAssignmentUid,
  });

  internal void CopyContentFrom(SystemConnection source, Func<String,bool> onFixedValueChangingCallback = null){
    this.SystemConnectionUid = source.SystemConnectionUid;
    this.OwnerInstituteUid = source.OwnerInstituteUid;
    this.HierSpäterJWTSEttings = source.HierSpäterJWTSEttings;
    this.TargetSystemEndpointUid = source.TargetSystemEndpointUid;
    this.DedicatedSiteRelatedSystemAssignmentUid = source.DedicatedSiteRelatedSystemAssignmentUid;
  }

  internal void CopyContentTo(SystemConnection target, Func<String,bool> onFixedValueChangingCallback = null){
    target.SystemConnectionUid = this.SystemConnectionUid;
    target.OwnerInstituteUid = this.OwnerInstituteUid;
    target.HierSpäterJWTSEttings = this.HierSpäterJWTSEttings;
    target.TargetSystemEndpointUid = this.TargetSystemEndpointUid;
    target.DedicatedSiteRelatedSystemAssignmentUid = this.DedicatedSiteRelatedSystemAssignmentUid;
  }

#endregion

}

public class InvolvedPersonEntity {

  /// <summary> An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more! </summary>
  [Required]
  public Guid InvolvedPersonUid { get; set; } = Guid.NewGuid();

  /// <summary> *this field is optional (use null as value) </summary>
  public String DisplayLabel { get; set; }

  /// <summary> *this field is optional </summary>
  public Nullable<Guid> EmailAddress { get; set; }

  [Required]
  public Boolean IsArchived { get; set; }

  [Referer]
  public virtual ObservableCollection<InvolvementRoleEntity> InvolvementRoles { get; set; } = new ObservableCollection<InvolvementRoleEntity>();

#region Mapping

  internal static Expression<Func<InvolvedPerson, InvolvedPersonEntity>> InvolvedPersonEntitySelector = ((InvolvedPerson src) => new InvolvedPersonEntity {
    InvolvedPersonUid = src.InvolvedPersonUid,
    DisplayLabel = src.DisplayLabel,
    EmailAddress = src.EmailAddress,
    IsArchived = src.IsArchived,
  });

  internal static Expression<Func<InvolvedPersonEntity, InvolvedPerson>> InvolvedPersonSelector = ((InvolvedPersonEntity src) => new InvolvedPerson {
    InvolvedPersonUid = src.InvolvedPersonUid,
    DisplayLabel = src.DisplayLabel,
    EmailAddress = src.EmailAddress,
    IsArchived = src.IsArchived,
  });

  internal void CopyContentFrom(InvolvedPerson source, Func<String,bool> onFixedValueChangingCallback = null){
    this.InvolvedPersonUid = source.InvolvedPersonUid;
    this.DisplayLabel = source.DisplayLabel;
    this.EmailAddress = source.EmailAddress;
    this.IsArchived = source.IsArchived;
  }

  internal void CopyContentTo(InvolvedPerson target, Func<String,bool> onFixedValueChangingCallback = null){
    target.InvolvedPersonUid = this.InvolvedPersonUid;
    target.DisplayLabel = this.DisplayLabel;
    target.EmailAddress = this.EmailAddress;
    target.IsArchived = this.IsArchived;
  }

#endregion

}

public class InvolvementRoleEntity {

  /// <summary> An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more! </summary>
  [Required]
  public Guid InvolvedPersonRoleUid { get; set; } = Guid.NewGuid();

  [Required]
  public Guid ResearchStudyUid { get; set; }

  /// <summary> *this field is optional (use null as value) </summary>
  public String Role { get; set; }

  /// <summary> *this field is optional </summary>
  public Nullable<DateTime> InvolvedFrom { get; set; }

  /// <summary> *this field is optional </summary>
  public Nullable<DateTime> InvolvedUntil { get; set; }

  /// <summary> null indicated a site independent global role *this field is optional </summary>
  public Nullable<Guid> DedicatedToSiteUid { get; set; }

  [Required]
  public Guid InvolvedPersonUid { get; set; }

  [Lookup]
  public virtual InvolvedPersonEntity InvolvedPerson { get; set; }

  [Principal]
  public virtual ResearchStudyEntity ResearchStudy { get; set; }

  [Lookup]
  public virtual SiteEntity DedicatedToSite { get; set; }

#region Mapping

  internal static Expression<Func<InvolvementRole, InvolvementRoleEntity>> InvolvementRoleEntitySelector = ((InvolvementRole src) => new InvolvementRoleEntity {
    InvolvedPersonRoleUid = src.InvolvedPersonRoleUid,
    ResearchStudyUid = src.ResearchStudyUid,
    Role = src.Role,
    InvolvedFrom = src.InvolvedFrom,
    InvolvedUntil = src.InvolvedUntil,
    DedicatedToSiteUid = src.DedicatedToSiteUid,
    InvolvedPersonUid = src.InvolvedPersonUid,
  });

  internal static Expression<Func<InvolvementRoleEntity, InvolvementRole>> InvolvementRoleSelector = ((InvolvementRoleEntity src) => new InvolvementRole {
    InvolvedPersonRoleUid = src.InvolvedPersonRoleUid,
    ResearchStudyUid = src.ResearchStudyUid,
    Role = src.Role,
    InvolvedFrom = src.InvolvedFrom,
    InvolvedUntil = src.InvolvedUntil,
    DedicatedToSiteUid = src.DedicatedToSiteUid,
    InvolvedPersonUid = src.InvolvedPersonUid,
  });

  internal void CopyContentFrom(InvolvementRole source, Func<String,bool> onFixedValueChangingCallback = null){
    this.InvolvedPersonRoleUid = source.InvolvedPersonRoleUid;
    this.ResearchStudyUid = source.ResearchStudyUid;
    this.Role = source.Role;
    this.InvolvedFrom = source.InvolvedFrom;
    this.InvolvedUntil = source.InvolvedUntil;
    this.DedicatedToSiteUid = source.DedicatedToSiteUid;
    this.InvolvedPersonUid = source.InvolvedPersonUid;
  }

  internal void CopyContentTo(InvolvementRole target, Func<String,bool> onFixedValueChangingCallback = null){
    target.InvolvedPersonRoleUid = this.InvolvedPersonRoleUid;
    target.ResearchStudyUid = this.ResearchStudyUid;
    target.Role = this.Role;
    target.InvolvedFrom = this.InvolvedFrom;
    target.InvolvedUntil = this.InvolvedUntil;
    target.DedicatedToSiteUid = this.DedicatedToSiteUid;
    target.InvolvedPersonUid = this.InvolvedPersonUid;
  }

#endregion

}

public class StudyRelatedSystemAssignmentEntity {

  [Required]
  public Guid StudyRelatedSystemAssignmentUid { get; set; } = Guid.NewGuid();

  [Required]
  public Guid ResearchStudyUid { get; set; }

  [Required]
  public Guid SystemEndpointUid { get; set; }

  /// <summary> semicolon separated list of custom role-names </summary>
  [Required]
  public String CustomRoles { get; set; }

  [Principal]
  public virtual ResearchStudyEntity ResearchStudy { get; set; }

  [Lookup]
  public virtual SystemEndpointEntity SystemEndpoint { get; set; }

#region Mapping

  internal static Expression<Func<StudyRelatedSystemAssignment, StudyRelatedSystemAssignmentEntity>> StudyRelatedSystemAssignmentEntitySelector = ((StudyRelatedSystemAssignment src) => new StudyRelatedSystemAssignmentEntity {
    StudyRelatedSystemAssignmentUid = src.StudyRelatedSystemAssignmentUid,
    ResearchStudyUid = src.ResearchStudyUid,
    SystemEndpointUid = src.SystemEndpointUid,
    CustomRoles = src.CustomRoles,
  });

  internal static Expression<Func<StudyRelatedSystemAssignmentEntity, StudyRelatedSystemAssignment>> StudyRelatedSystemAssignmentSelector = ((StudyRelatedSystemAssignmentEntity src) => new StudyRelatedSystemAssignment {
    StudyRelatedSystemAssignmentUid = src.StudyRelatedSystemAssignmentUid,
    ResearchStudyUid = src.ResearchStudyUid,
    SystemEndpointUid = src.SystemEndpointUid,
    CustomRoles = src.CustomRoles,
  });

  internal void CopyContentFrom(StudyRelatedSystemAssignment source, Func<String,bool> onFixedValueChangingCallback = null){
    this.StudyRelatedSystemAssignmentUid = source.StudyRelatedSystemAssignmentUid;
    this.ResearchStudyUid = source.ResearchStudyUid;
    this.SystemEndpointUid = source.SystemEndpointUid;
    this.CustomRoles = source.CustomRoles;
  }

  internal void CopyContentTo(StudyRelatedSystemAssignment target, Func<String,bool> onFixedValueChangingCallback = null){
    target.StudyRelatedSystemAssignmentUid = this.StudyRelatedSystemAssignmentUid;
    target.ResearchStudyUid = this.ResearchStudyUid;
    target.SystemEndpointUid = this.SystemEndpointUid;
    target.CustomRoles = this.CustomRoles;
  }

#endregion

}

public class SiteRelatedSystemAssignmentEntity {

  [Required]
  public Guid SiteRelatedSystemAssignmentUid { get; set; } = Guid.NewGuid();

  [Required]
  public Guid SystemEndpointUid { get; set; }

  [Required]
  public Guid SiteUid { get; set; }

  /// <summary> semicolon separated list of custom role-names </summary>
  [Required]
  public String CustomRoles { get; set; }

  [Principal]
  public virtual SiteEntity Site { get; set; }

  [Lookup]
  public virtual SystemEndpointEntity SystemEndpoint { get; set; }

  [Referer]
  public virtual ObservableCollection<SystemConnectionEntity> DedicatedSystemConnection { get; set; } = new ObservableCollection<SystemConnectionEntity>();

#region Mapping

  internal static Expression<Func<SiteRelatedSystemAssignment, SiteRelatedSystemAssignmentEntity>> SiteRelatedSystemAssignmentEntitySelector = ((SiteRelatedSystemAssignment src) => new SiteRelatedSystemAssignmentEntity {
    SiteRelatedSystemAssignmentUid = src.SiteRelatedSystemAssignmentUid,
    SystemEndpointUid = src.SystemEndpointUid,
    SiteUid = src.SiteUid,
    CustomRoles = src.CustomRoles,
  });

  internal static Expression<Func<SiteRelatedSystemAssignmentEntity, SiteRelatedSystemAssignment>> SiteRelatedSystemAssignmentSelector = ((SiteRelatedSystemAssignmentEntity src) => new SiteRelatedSystemAssignment {
    SiteRelatedSystemAssignmentUid = src.SiteRelatedSystemAssignmentUid,
    SystemEndpointUid = src.SystemEndpointUid,
    SiteUid = src.SiteUid,
    CustomRoles = src.CustomRoles,
  });

  internal void CopyContentFrom(SiteRelatedSystemAssignment source, Func<String,bool> onFixedValueChangingCallback = null){
    this.SiteRelatedSystemAssignmentUid = source.SiteRelatedSystemAssignmentUid;
    this.SystemEndpointUid = source.SystemEndpointUid;
    this.SiteUid = source.SiteUid;
    this.CustomRoles = source.CustomRoles;
  }

  internal void CopyContentTo(SiteRelatedSystemAssignment target, Func<String,bool> onFixedValueChangingCallback = null){
    target.SiteRelatedSystemAssignmentUid = this.SiteRelatedSystemAssignmentUid;
    target.SystemEndpointUid = this.SystemEndpointUid;
    target.SiteUid = this.SiteUid;
    target.CustomRoles = this.CustomRoles;
  }

#endregion

}

}
