using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using H7 = Hl7.Fhir.Model;

namespace MedicalResearch.SubjectData.Model {

  #region " Model "

  public abstract class SubjectMetaRecord {

    /// <summary>
    /// An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see>
    /// which can be generated by any origin system and is used to address this ORSCF conform data record in
    /// decentralized environments. Note that this Identity must not be changed any more!
    /// </summary>
    [Required]
    public Guid SubjectUid { get; set; } = Guid.Empty;

    /// <summary> 
    /// identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem'
    /// (the exact semantic is defined per study)
    /// *this field has a max length of 100
    /// </summary>
    [FixedAfterCreation, MaxLength(100), Required]
    public String SubjectIdentifier { get; set; }

    #region " Principals & Scopes "

    [Required]
    public Guid StudyUid { get; set; } = Guid.Empty;

    [Required]
    public Guid ActualSiteUid { get; set; } = Guid.Empty;

    #endregion

    /// <summary>
    /// This is an internal managed field, which is related to the state of records dedicated to the database.
    /// It will be automatically set when a record is archived. A mapping during data import requires opt-in.
    /// </summary>
    [Required]
    public bool IsArchived { get; set; } = false;

    /// <summary>
    /// This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database.
    /// It will be automatically set to the current time when a record is created, updated, archived or unarchived,
    /// but cannot be updated from outside and must not be mapped during data imports.
    /// </summary>
    [Required]
    public long ModificationTimestampUtc { get; set; } = 0;

  }

  public partial class SubjectFields : SubjectMetaRecord {

    [FixedAfterCreation, Required]
    public Guid EnrollingSiteUid { get; set; }

    /// <summary> 
    /// AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>:
    /// candidate | eligible | follow-up | ineligible | not-registered | off-study | 
    /// on-study | on-study-intervention | on-study-observation | pending-on-study | 
    /// potential-candidate | screening | withdrawn 
    /// </summary>
    [Required]
    public String Status { get; set; }

    /// <summary>
    /// a note (manually written text) which provides some additional
    /// information about the reason why one transitioned to 
    /// the current status
    /// </summary>
    public String StatusNote { get; set; }

    public DateTime PeriodStart { get; set; }

    public DateTime PeriodEnd { get; set; }

    public String AssignedArm { get; set; }

    public String ActualArm { get; set; }

    public String[] SubstudyNames { get; set; }

    /// <summary> This can be the ID ('surrogate-key') of the Partient record within a site specific
    /// patient management system. This MUST NOT be any natural key or plain readable name which 
    /// exposes the identity of the patient! </summary>
    public String ActualSiteDefinedPatientIdentifier { get; set; }

    /// <summary>
    /// Custom fields as defined by the Service.
    /// Call 'GetCustomFieldDescriptors' to get information about supported/required fields.
    /// Any passed values for undefined fields will be ignored.
    /// </summary>
    public Dictionary<string, string> CustomFields { get; set; } = new Dictionary<string, string>();

  }

  /// The full structure of an ORSCF qualified 'Subject' containing all
  /// essential fields and the tree of dependend childs
  public class SubjectStructure : SubjectFields {

    //public DataRecordingStructure[] DataRecordings { get; set; } = new DataRecordingStructure[] {};

  }

  /// <summary>
  /// A structure containing HL7/FHIR-Ressources (JSON only) and
  /// the essential fields which are required to qualify a ORSCF record.
  /// </summary>
  public class SubjectFhirRessourceContainer : SubjectMetaRecord {

    /// <summary>a HL7 <see href="https://www.hl7.org/fhir/researchsubject.html">'ResearchSubject'</see> resource in json format</summary>
    public Dictionary<string, Object> ResearchSubjectRessource { get; set; } = null;

  }

  #endregion

  #region " Filter "

  public class SubjectFilter {

    public UidFieldFilter StudyUid { get; set; } = null;

    public UidFieldFilter SiteUid { get; set; } = null;

    /// <summary> 
    /// identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem'
    /// (the exact semantic is defined per study)
    /// *this field has a max length of 100
    /// </summary>
    public StringFieldFilter SubjectIdentifier { get; set; }

    #region " Content "

    /// <summary> 
    /// AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>:
    /// candidate | eligible | follow-up | ineligible | not-registered | off-study | 
    /// on-study | on-study-intervention | on-study-observation | pending-on-study | 
    /// potential-candidate | screening | withdrawn 
    /// </summary>
    public StringFieldFilter Status { get; set; }

    public DateFieldFilter PeriodStart { get; set; }

    public DateFieldFilter PeriodEnd { get; set; }

    public StringFieldFilter AssignedArm { get; set; }

    public StringFieldFilter ActualArm { get; set; }

    public StringFieldFilter SubstudyName { get; set; }

    /// <summary> This can be the ID ('surrogate-key') of the Partient record within a site specific
    /// patient management system. This MUST NOT be any natural key or plain readable name which 
    /// exposes the identity of the patient! </summary>
    public StringFieldFilter ActualSiteDefinedPatientIdentifier { get; set; }

    #endregion

    /// <summary>
    /// Custom fields as defined by the Service.
    /// Call 'GetCustomFieldDescriptors' to get information about supported/required fields.
    /// Any passed values for undefined fields will be ignored.
    /// </summary>
    public Dictionary<string, StringFieldFilter> CustomFields { get; set; } = null;

  }

  #endregion

  #region " Mutations "

  public partial class BatchableSubjectMutation {

    /// <summary> 
    /// AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>:
    /// candidate | eligible | follow-up | ineligible | not-registered | off-study | 
    /// on-study | on-study-intervention | on-study-observation | pending-on-study | 
    /// potential-candidate | screening | withdrawn 
    /// </summary>
    public String Status { get; set; }

    public String AssignedArm { get; set; }

    public String ActualArm { get; set; }

    public DateTime? PeriodStart { get; set; }

    public DateTime? PeriodEnd { get; set; }

    /// <summary>
    /// Custom fields as defined by the Service.
    /// Call 'GetCustomFieldDescriptors' to get information about supported/required fields.
    /// Any passed values for undefined fields will be ignored.
    /// </summary>
    public Dictionary<string, string> CustomFields { get; set; } = new Dictionary<string, string>();

  }

  public partial class SubjectMutation : BatchableSubjectMutation {

    /// <summary>
    /// a note (manually written text) which provides some additional
    /// information about the reason why one transitioned to 
    /// the current status
    /// </summary>
    public String StatusNote { get; set; }

    public String[] SubstudyNames { get; set; }

    /// <summary> This can be the ID ('surrogate-key') of the Partient record within a site specific
    /// patient management system. This MUST NOT be any natural key or plain readable name which 
    /// exposes the identity of the patient! </summary>
    public String ActualSiteDefinedPatientIdentifier { get; set; }

  }

  #endregion

}
